# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfYgqd2n4HI_Sbk8vfxsdyWq1RasAr8o
"""

import pandas as pd
import random
import math
import time
import matplotlib.pyplot as plt
from google.colab import files

# Upload dataset
uploaded = files.upload()
df = pd.read_csv("VRPTW_dataset_100.csv")
df.head()

# Extract coordinates
clients = list(zip(df['x'], df['y']))

def distance(p1, p2):
    return math.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2)

def total_distance(solution, clients):
    total = 0
    for i in range(len(solution)-1):
        total += distance(clients[solution[i]], clients[solution[i+1]])
    return total

def generate_neighbors(solution):
    neighbors = []
    for i in range(len(solution)):
        for j in range(i+1, len(solution)):
            new_solution = solution.copy()
            new_solution[i], new_solution[j] = new_solution[j], new_solution[i]
            neighbors.append((new_solution, (i,j)))
    return neighbors

def tabu_search(clients, max_iter=50, tabu_size=10):

    n = len(clients)
    current_solution = list(range(n))
    random.shuffle(current_solution)

    best_solution = current_solution
    best_cost = total_distance(current_solution, clients)

    tabu_list = []

    for _ in range(max_iter):

        neighbors = generate_neighbors(current_solution)
        neighbors = sorted(neighbors, key=lambda x: total_distance(x[0], clients))

        for neighbor, move in neighbors:
            if move not in tabu_list:

                current_solution = neighbor
                current_cost = total_distance(current_solution, clients)

                if current_cost < best_cost:
                    best_solution = current_solution
                    best_cost = current_cost

                tabu_list.append(move)

                if len(tabu_list) > tabu_size:
                    tabu_list.pop(0)

                break

    return best_solution, best_cost

start = time.time()
best_solution, best_cost = tabu_search(clients, max_iter=50, tabu_size=10)
end = time.time()

print("Distance totale :", best_cost)
print("Temps d'exécution :", end - start)

sol = best_solution
x = [clients[i][0] for i in sol] + [clients[sol[0]][0]]
y = [clients[i][1] for i in sol] + [clients[sol[0]][1]]

plt.figure(figsize=(8,6))
plt.plot(x, y, marker='o', color='blue')
plt.title("Meilleure tournée - Recherche Tabou")
plt.xlabel("X")
plt.ylabel("Y")
plt.show()

print("""
=== Question 1 : Pseudo-code ===
(voir rapport ci-dessus)

=== Question 2 : Paramètres ===
max_iter : nombre d'itérations
tabu_size : taille de la liste tabou
solution initiale : point de départ
voisinage : swap

=== Question 3 : Application ===
Dataset : VRPTW_dataset_100.c
sv (100 clients)
Distance totale obtenue : {:.2f}
Temps d'exécution : {:.2f} s

=== Question 4 : Complexité ===
Complexité = O(MaxIter × n^3)
""".format(best_cost, end-start))